/*
 * Snap Conversions API V3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.snap.business.sdk.v3.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.snap.business.sdk.v3.model.CapiEvent;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.snap.business.sdk.v3.JSON;

/**
 * EventMetadata
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class EventMetadata {
  public static final String SERIALIZED_NAME_PIXEL_ID = "pixel_id";
  @SerializedName(SERIALIZED_NAME_PIXEL_ID)
  private String pixelId;

  public static final String SERIALIZED_NAME_SNAP_APP_ID = "snap_app_id";
  @SerializedName(SERIALIZED_NAME_SNAP_APP_ID)
  private String snapAppId;

  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_CONVERSION_INFO = "conversion_info";
  @SerializedName(SERIALIZED_NAME_CONVERSION_INFO)
  private CapiEvent conversionInfo;

  public EventMetadata() {
  }

  public EventMetadata pixelId(String pixelId) {
    this.pixelId = pixelId;
    return this;
  }

  /**
   * Get pixelId
   * @return pixelId
   */
  @javax.annotation.Nullable
  public String getPixelId() {
    return pixelId;
  }

  public void setPixelId(String pixelId) {
    this.pixelId = pixelId;
  }


  public EventMetadata snapAppId(String snapAppId) {
    this.snapAppId = snapAppId;
    return this;
  }

  /**
   * Get snapAppId
   * @return snapAppId
   */
  @javax.annotation.Nullable
  public String getSnapAppId() {
    return snapAppId;
  }

  public void setSnapAppId(String snapAppId) {
    this.snapAppId = snapAppId;
  }


  public EventMetadata appId(String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }


  public EventMetadata conversionInfo(CapiEvent conversionInfo) {
    this.conversionInfo = conversionInfo;
    return this;
  }

  /**
   * Get conversionInfo
   * @return conversionInfo
   */
  @javax.annotation.Nullable
  public CapiEvent getConversionInfo() {
    return conversionInfo;
  }

  public void setConversionInfo(CapiEvent conversionInfo) {
    this.conversionInfo = conversionInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventMetadata eventMetadata = (EventMetadata) o;
    return Objects.equals(this.pixelId, eventMetadata.pixelId) &&
        Objects.equals(this.snapAppId, eventMetadata.snapAppId) &&
        Objects.equals(this.appId, eventMetadata.appId) &&
        Objects.equals(this.conversionInfo, eventMetadata.conversionInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pixelId, snapAppId, appId, conversionInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventMetadata {\n");
    sb.append("    pixelId: ").append(toIndentedString(pixelId)).append("\n");
    sb.append("    snapAppId: ").append(toIndentedString(snapAppId)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    conversionInfo: ").append(toIndentedString(conversionInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pixel_id");
    openapiFields.add("snap_app_id");
    openapiFields.add("app_id");
    openapiFields.add("conversion_info");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventMetadata
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventMetadata.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventMetadata is not found in the empty JSON string", EventMetadata.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventMetadata.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EventMetadata` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("pixel_id") != null && !jsonObj.get("pixel_id").isJsonNull()) && !jsonObj.get("pixel_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pixel_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pixel_id").toString()));
      }
      if ((jsonObj.get("snap_app_id") != null && !jsonObj.get("snap_app_id").isJsonNull()) && !jsonObj.get("snap_app_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `snap_app_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("snap_app_id").toString()));
      }
      if ((jsonObj.get("app_id") != null && !jsonObj.get("app_id").isJsonNull()) && !jsonObj.get("app_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `app_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("app_id").toString()));
      }
      // validate the optional field `conversion_info`
      if (jsonObj.get("conversion_info") != null && !jsonObj.get("conversion_info").isJsonNull()) {
        CapiEvent.validateJsonElement(jsonObj.get("conversion_info"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventMetadata.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventMetadata' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventMetadata> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventMetadata.class));

       return (TypeAdapter<T>) new TypeAdapter<EventMetadata>() {
           @Override
           public void write(JsonWriter out, EventMetadata value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventMetadata read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventMetadata given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventMetadata
   * @throws IOException if the JSON string is invalid with respect to EventMetadata
   */
  public static EventMetadata fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventMetadata.class);
  }

  /**
   * Convert an instance of EventMetadata to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

