/*
 * Snap Conversions API V3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.snap.business.sdk.v3.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.snap.business.sdk.v3.JSON;

/**
 * StatsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class StatsResponse {
  public static final String SERIALIZED_NAME_LATEST_EVENT_TS = "latest_event_ts";
  @SerializedName(SERIALIZED_NAME_LATEST_EVENT_TS)
  @javax.annotation.Nullable
  private Long latestEventTs;

  public static final String SERIALIZED_NAME_EVENT_COUNT_PAST_HOUR = "event_count_past_hour";
  @SerializedName(SERIALIZED_NAME_EVENT_COUNT_PAST_HOUR)
  @javax.annotation.Nullable
  private Long eventCountPastHour;

  public StatsResponse() {
  }

  public StatsResponse latestEventTs(@javax.annotation.Nullable Long latestEventTs) {
    this.latestEventTs = latestEventTs;
    return this;
  }

  /**
   * Get latestEventTs
   * @return latestEventTs
   */
  @javax.annotation.Nullable
  public Long getLatestEventTs() {
    return latestEventTs;
  }

  public void setLatestEventTs(@javax.annotation.Nullable Long latestEventTs) {
    this.latestEventTs = latestEventTs;
  }


  public StatsResponse eventCountPastHour(@javax.annotation.Nullable Long eventCountPastHour) {
    this.eventCountPastHour = eventCountPastHour;
    return this;
  }

  /**
   * Get eventCountPastHour
   * @return eventCountPastHour
   */
  @javax.annotation.Nullable
  public Long getEventCountPastHour() {
    return eventCountPastHour;
  }

  public void setEventCountPastHour(@javax.annotation.Nullable Long eventCountPastHour) {
    this.eventCountPastHour = eventCountPastHour;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsResponse statsResponse = (StatsResponse) o;
    return Objects.equals(this.latestEventTs, statsResponse.latestEventTs) &&
        Objects.equals(this.eventCountPastHour, statsResponse.eventCountPastHour);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latestEventTs, eventCountPastHour);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsResponse {\n");
    sb.append("    latestEventTs: ").append(toIndentedString(latestEventTs)).append("\n");
    sb.append("    eventCountPastHour: ").append(toIndentedString(eventCountPastHour)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("latest_event_ts");
    openapiFields.add("event_count_past_hour");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StatsResponse is not found in the empty JSON string", StatsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StatsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<StatsResponse>() {
           @Override
           public void write(JsonWriter out, StatsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatsResponse
   * @throws IOException if the JSON string is invalid with respect to StatsResponse
   */
  public static StatsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatsResponse.class);
  }

  /**
   * Convert an instance of StatsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

